### ISSUE TITLE
Link to node.js is a deprecated project

### ISSUE THREAD

**Issue by bersling** [mustache/mustache.github.com#100]
I would suggest removing the link to "node.js" (leading to https://github.com/raycmorgan/Mu) on the https://mustache.github.io/ page. That project seems to be abandoned, the author hasn't commited anything in over a year and there are four open pull requests. One of them is by me, the author has never responded. I'm suggesting to remove that link, since the project linked under "JavaScript" (https://github.com/janl/mustache.js) also has a node.js command line tool. So the link under "node.js" is actually just a less maintained version of the "JavaScript" link.

**Comment by locks** [comment]
Thanks for the heads up!
