### ISSUE TITLE
Optional variables

### ISSUE THREAD

**Issue by walec51** [mustache/mustache.github.com#101]
Many mustache implementations throw an error if a referenced variable has a null value.
However this is z common case: print the value if it is not null.
Now we can handle this by the following syntax:

{{#someVariableA}}{{.}}{{/someVariableA}}

I suggest to introduce the following syntax sugar to replace the following:

{{?someVariableA}}

**Comment by jgonggrijp** [comment]
Closing this because this repository is about the website and not about the Mustache template language. Please take comments about the template language to https://github.com/mustache/spec/discussions.
