### ISSUE TITLE
Broken link in the documentation

### ISSUE THREAD

**Issue by Arthur-Milchior** [mustache/mustache.github.com#102]
Hi,

FYI, in https://mustache.github.io/mustache.5.html the link ctemplates to http://google-ctemplate.googlecode.com/svn/trunk/doc/howto.html is broken

**Comment by franklinyu** [comment]
Some one forked Google CTemplate, and this is available in <https://github.com/OlafvdSpek/ctemplate/blob/master/doc/reference.html> (rendered in <https://htmlpreview.github.io/?https://raw.githubusercontent.com/OlafvdSpek/ctemplate/master/doc/reference.html>).

The URL is ugly, so I proposed OlafvdSpek/ctemplate#133.

**Comment by jgonggrijp** [comment]
Link is no longer broken on website.
