### ISSUE TITLE
How do mustache avoid xss attack? 

### ISSUE THREAD

**Issue by PEIYANGXINQU** [mustache/mustache.github.com#106]
At first ,I use doT.js,It seems that doT do not check the input content.If the content is alert(999)</script>,then it will execute and alert the window. Now I change to use mustache.js.It seems OK.How do mustache avoid xss attack?

**Comment by franklinyu** [comment]
>All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: `{{{name}}}`.
>
>You can also use `&` to unescape a variable: `{{& name}}`. This may be useful when changing delimiters (see "Set Delimiter" below).

From [manual](https://mustache.github.io/mustache.5.html).

In addition, you may want to report directly to [mustache.js](https://github.com/janl/mustache.js).
