### ISSUE TITLE
How is multi-line content handled?

### ISSUE THREAD

**Issue by Snafuuz** [mustache/mustache.github.com#108]
What should I do if my content can contain line breaks?
In general, content is HTML encoded while rendering, but that does not affect \n

What should I do if my content is a multi-line string?
- pre-process the text, replacing newlines by <br> tags?
=> then I cannot use mustache's built-in HTML encoding for the content, as it would HTML-encode each <br> tag to &lt;br&gt;

- post-process the rendered output, replacing newlines by <br>?
=> I might incorrectly encode newlines which were not part of any content

- Do all the HTML encoding of my content myself, so I can convert newlines to <br> and then use a triple{{{}}} tag for my content 
=> this seems to be the only working solution, but it seems a little cumbersome

Since content is HTML-encoded by default, wouldn't it make sense then, to also convert newlines in content to <br> tags?

**Comment by jgonggrijp** [comment]
Escaping of interpolation tags is the only situation where Mustache makes assumptions about the target language. Other than that, it's on you. If Mustache started inserting HTML tags, that would break the template language for many users.

Closing this, as this repository is only about the Mustache website, not about the template language.
