### ISSUE TITLE
Unrendered MD Link in mustache(5)

### ISSUE THREAD

**Issue by tajmone** [mustache/mustache.github.com#110]
For some reason, the ERB link in `mustache(5)` (in __Partials__) is not being rendered as expected:

    They also inherit the calling context. Whereas in an [ERB]
    (http://en.wikipedia.org/wiki/ERuby) file you may have this:

It looks like the markdown link was not rendered but carried over verbatim to HTML:

- https://github.com/mustache/mustache.github.com/blob/a0fcda1/mustache.5.html#L351

I couldn't figure which is the markdown source file used to build that page, otherwise I'd have made a PR to fix it.

**Comment by tajmone** [comment]
Probably it's due to indentation, the block being treated as a verbatim `<pre>` block, so the markdown link is not getting parsed.

In the [mustache repo] this problem is not present, as there is no link to Wikipedia's ERB page in that paragraph:

- https://github.com/mustache/mustache/blob/master/man/mustache.5.ron#L255

```
They also inherit the calling context. Whereas in ERB you may have
this: 
```

[mustache repo]: https://github.com/mustache/mustache

**Comment by jgonggrijp** [comment]
The problem was that the website does not (yet) automatically update when the manpages are updated in the mustache/mustache repository. As of November 2023, the manpage is current again and the broken link is no longer present.
