### ISSUE TITLE
Freenode: nobody in the channel knows mustache

### ISSUE THREAD

**Issue by tobwen** [mustache/mustache.github.com#113]
Seems like the IRC channel on Freenode got abandoned. Nobody in there has ever heard of mustache :-)

**Comment by markand** [comment]
Perhaps add a topic.

**Comment by tobwen** [comment]
Me? Actually, this information seems to be outdated for about 4 years:
https://github.com/mustache/mustache.github.com/blob/6f2d957efe5553580324575e314c1e1afcd3d275/index.html#L91

**Comment by markand** [comment]
I think mustache itself is dying.

**Comment by tobwen** [comment]
> I think mustache itself is dying.
You mean, it gets shaved :)
