### ISSUE TITLE
linebreaks / empty vars in plain text files

### ISSUE THREAD

**Issue by DaafSamson** [mustache/mustache.github.com#114]
Hi,
I'm using Mustache to merge plain text templates.
I have the following scenario:

**data**
```
{
"name":"James"
,"colour":"green"
,"book":"War and peace"
}
```

**template**
```
This is what we know about {{name}}: 
{{#colour}}- Favourite colour is {{colour}}{{/colour}}
{{#fruit}}- Favourite fruit is {{fruit}}{{/fruit}}
{{#book}}- Favourite book is {{book}}{{/book}}
```

**Result:**
```
This is what we know about James: 
- Favourite colour is green

- Favourite book is War and peace
```

Note the glaring gap between the two lines...
Now, in a HTML template this would not be and issue, white spaces and empty lines are eaten by the browser and the result flows nicely. In a plain text environment though, this is an issue.

Is there an established way to deal with this? Is there a construct that drops the line including the line break after the field?

**Comment by vanta** [comment]
Any update here? Noone with the same problem?

**Comment by jobol** [comment]
I had to change mustach to fix a compatibility with the spec (see https://gitlab.com/jobol/mustach/-/issues/30)

Spec is: a line with a standalone tag is not emitted.

So writing your template as below should make the job

```
This is what we know about {{name}}: 
{{#colour}}
- Favourite colour is {{colour}}
{{/colour}}
{{#fruit}}
- Favourite fruit is {{fruit}}
{{/fruit}}
{{#book}}
- Favourite book is {{book}}
{{/book}}
```

I removed the ```{| |}``` so this is perhaps not a valuable solution in that case ....

**Comment by jgonggrijp** [comment]
The above solution is correct. Closing this, as this repository is only about the Mustache website, not about the template language.
