### ISSUE TITLE
How to escape a partial's output?

### ISSUE THREAD

**Issue by mesztam** [mustache/mustache.github.com#118]
Hi,
is there any way to escape the output of a partial? E.g. when using the output of the partial as the value of an attribute like this:
`<input type="hidden" value="{{> generateHtml }} "/>`
Thanks in advance!

**Comment by leonardopsantos** [comment]
I'm sorry, I don't quite follow you there. Can you expand your code with an example of something you wanted escaped, preferably with code so we can try to reproduce it?

My (limited) experience with Mustache (pystache) was that it escapes HTML elements (thus breaking them). So I had to tell Mustache not to escape things with `{{{}}}`.

**Comment by leonardopsantos** [comment]
I tested this with pystache and partials are escaped:

```python
context =\
{
    'users' : [
        {'name': 'John',
         'job' : 'Engineer'},
        {'name': 'Leo',
         'job' : 'Coder<br>'}
    ]
}

full_template =\
'''
{{#users}}
{{name}} is an {{job}}
{{/users}} 
'''

renderer = pystache.Renderer()

output = renderer.render(full_template, context)
print(output)

print("The same data now as a partial:\n")

output = renderer.render_path('base.mustache', context)
print(output)
```

The above produces:

```
John is an Engineer
Leo is an Coder&lt;br&gt;
```

With partials:

```python
base_template =\
'''
{{#users}}
{{> user}}
{{/users}} 
'''

print("The same data now as a partial with a path:\n")

output = renderer.render(base_template, context)
print(output)
```

user.mustache:

```
{{name}} is an {{job}}
```

Produces:

```
John is an Engineer
Leo is an Coder&lt;br&gt;
```

**Comment by jgonggrijp** [comment]
The spec does not state whether partials should be escaped or not. Some implementations do, some don't. Some might have a triple-mustache variant of every tag type so each can be either escaped or not escaped.

If you believe that something should be standardized, you can take it to https://github.com/mustache/spec/discussions.

Closing this, as this repository is only about the Mustache website, not about the template language.
