### ISSUE TITLE
Mustache-ES6

### ISSUE THREAD

**Issue by ppKrauss** [mustache/mustache.github.com#119]
Mustache is an important template system for Web and non-Web applications... But Javascript is also a great inspiration and reference, for JSON and Mustache. Javascript evolved, particularly  with the ECMA's v6 edition, "ES6". Currently, the `${x}` of the [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) is a [*de facto* standard](https://en.wikipedia.org/wiki/De_facto_standard).

The adoption of `{{x}}` was a good choice (it resembles the Mediawiki templates), and there is no problem with it... But it was arbitrary, before 2015 there was no  Javascript-reference &mdash; that's an important part of the "standards ecosystem".  Now, maybe, we can try to restart with non-arbitrary choice.

**Question and suggestion**: is it possible (or "are there people in this community?") to create a fork **by Mustache iniciative** (suggested name "Mustache-ES6") to test and evolve to the new standard?

-----

PS: about particular Javascript implementation and optimizations, see  this [es6-template-engine](https://github.com/dondido/express-es6-template-engine) project.

**Comment by locks** [comment]
Hi @ppKrauss. I am not sure what exactly you want to suggest? Mustache is meant to be used in many different programming languages, so using JavaScript interpolation, with access to the entire JavaScript language, seems like a poor fit for Mustache.
I encourage you to fork and experiment, who knows what you might come up with!
