### ISSUE TITLE
use value from list based on another key

### ISSUE THREAD

**Issue by karlismelderis** [mustache/mustache.github.com#124]
Hello, Everyone

Sorry if the question is already answered somewhere or it's too trivial.
I'm looking for a way to use a value from the list based on another value
e.g.
```javascript
system: {
latest: v2
}

systems: {
v1: {
item: 1
},
v2: {
item: 111
}
}
```
and in markdown:
```javascript
{{systems.{{system.latest}}.item}}
```
:) syntax doesn't work but I hope it will help to show where I'm heading.

**Comment by jgonggrijp** [comment]
This is not trivial. It is also not a very common use case, so I don't think there are many answers lying around.

I would strongly recommend that you add a `latest` key to `systems`, which has a copy/reference to `systems[system.lastest]`, before feeding the data into the template. Preprocessing the data is often the answer to questions like these.

If, for whatever reason, preprocessing the data is really not an option, I don't think there is a standard solution. It seems like a potential use case for dynamic names inside interpolation tags, but this is controversial. You can find previous discussion about this via https://github.com/mustache/spec/pull/134.

Closing this, as this repository is only about the Mustache website, not about the template language.
