### ISSUE TITLE
Appending random string starting with 'm_-' to classes after rendering the template

### ISSUE THREAD

**Issue by D0NNY** [mustache/mustache.github.com#125]
When adding styles classes to a template, after rendering the template in html the class name of each class get appended by a random string starting with 'm_-' which will not render the css
![64025348-1b7a3600-cb5a-11e9-8479-f1da4bab34dc](https://user-images.githubusercontent.com/29435936/64937848-7fe70600-d879-11e9-9f42-6beccf66c925.png)

**Comment by jgonggrijp** [comment]
Closing this, as this repository is only about the Mustache website, not about whatever Mustache engine is giving you this problem. If your problem is still unresolved, please take it to the issue tracker of that implementation.
