### ISSUE TITLE
Context name from list

### ISSUE THREAD

**Issue by leonardopsantos** [mustache/mustache.github.com#136]
I'm trying to render a list of values. In my real problem, each list item has a `name` property, and also another list, in which the items also have a 'name' property. I'm trying to avoid renaming the nested list items in my context.

I've done some testing and I figure out that this works perfectly:

```
        template = '''
{{#my_list}}
My list name is: {{my_list.name}}
{{/my_list}}
'''
        context = {'my_list' : {'name': 'This is my first item'}}

        renderer = pystache.Renderer(missing_tags='strict')
        s = renderer.render(template, context)
        print(s)
```

The output is what you expect:

```
My list name is: This is my first item
```

However, if `my_list` is actually a list (like it is in my actual problem), this breaks:

```
        context = {'my_list' : [
                {'name': 'This is my first item'},
                {'name': 'This is my second item'}
            ]}
```
I've tried with Pystache and Chevron, and they don't work, I get:

```
My list name is: 
My list name is:
```

My question is: should it work according to the specs?

Thanks a lot!

**Comment by jobol** [comment]
Have you tried to put {{name}} instead of {{my_list.name}} ?
If no then try.

**Comment by leonardopsantos** [comment]
My goal with this is to try to solve this problem:

```
template = '''
{{#my_list}}
{{#sublist}}
{{name}} from {{name}}
{{/sublist}}
{{/my_list}}
'''

context = {'my_list' : [
        {'name': 'list first item',
         'sublist' : [
             {'name': 'sublist first item'},
             {'name': 'sublist second item'}
          ]},
        {'name': 'list second item',
         'sublist' : [
             {'name': 'sublist first item'},
             {'name': 'sublist second item'}
          ]}
    ]}
```

And I want this rendered:

```
sublist first item from list first item
sublist second item from list first item
sublist first item from list second item
sublist second item from list second item
```

But I get this rendered:

```
sublist first item from sublist first item
sublist second item from sublist second item
list second item from list second item
list second item from list second item
```

I thought that having a template with named elements would solve my problem:

```
template = '''
{{#my_list}}
{{#sublist}}
{{sublist.name}} from {{my_list.name}}
{{/sublist}}
{{/my_list}}
'''
```

**Comment by jobol** [comment]
Are you forced to use the same key 'name'?

**Comment by leonardopsantos** [comment]
>  I'm trying to avoid renaming the nested list items in my context.

Yes, I'd like to keep using the same name.

**Comment by jobol** [comment]
In your example, there is a blind array index in my_list[].name and sublist[].name 

That is obvious but implicit. At the end if it works, it should remain implicit i guess

**Comment by leonardopsantos** [comment]
> In your example, there is a blind array index in my_list[].name and sublist[].name
> 
> That is obvious but implicit. At the end if it works, it should remain implicit i guess

I'm not sure what you mean by 'At the end if it works'. It doesn't work.

Is this something that should be supported by the specs?

Thanks!

**Comment by leonardopsantos** [comment]
My current 'solution' is to name every single list element:

```
template = '''
{{#my_list}}
{{#my_list_item.sublist}}
{{name}} from {{my_list_item.name}}
{{/my_list_item.sublist}}
{{/my_list}}
'''

context = {'my_list' : [
        { 'my_list_item' : 
            {'name': 'list first item',
             'sublist' : [
                 {'name': 'sublist first item'},
                 {'name': 'sublist second item'}
                 ]
            }
        },
        { 'my_list_item' : 
            {'name': 'list second item',
             'sublist' : [
                 {'name': 'sublist first item'},
                 {'name': 'sublist second item'}
              ]
            }
        }
    ]}
```

**Comment by phspies** [comment]
I'm hiving the same issue with nested arrays. This fiddle shows how the nested loops cannot cross access each other's objects: http://jsfiddle.net/L0zak1x8/7/

**Comment by jgonggrijp** [comment]
This is an unsolved problem in the Mustache language. Some implementations offer solutions, but there is no standard solution yet.

You can find previous discussion about this issue via https://github.com/mustache/spec/discussions/154.

Closing this, as this repository is only about the Mustache website, not about the template language.
