### ISSUE TITLE
How to output raw moustache in a code block?

### ISSUE THREAD

**Issue by kevquirk** [mustache/mustache.github.com#155]
Hey folks,

I'm hoping get a little help please. I'm using Moustache on a project, and I'm trying to reference some raw moustache within a code block in documentation. However, when the page is rendered, the moustache is processed and the code blocks contain the output, rather than the raw moustache.

In Jekyll, they allow you to wrap liquid in `{{ raw }}...{{ endraw }}` so that raw liquid syntax can be rendered. Does such a thing exist in Moustache?

Thanks!

**Comment by jobol** [comment]
You can set the delimiters: {{=<% %>=}}   .....MY ESCAPED MUSTACHE...  <%={{ }}=%>

**Comment by kevquirk** [comment]
That worked perfectly. Thanks for the really quick reply. :+1:
