### ISSUE TITLE
The C# version is incompatible

### ISSUE THREAD

**Issue by ubershmekel** [mustache/mustache.github.com#61]
Why is `mustache-sharp` linked as though it's an implementation of mustache?

https://github.com/jehugaleahsa/mustache-sharp

There's a special `#each` tag that loops. You get an error for doing loops the normal mustache way `Encountered an unknown tag: {{#files}}. It was either not registered or exists in a different context.`. It even has an `if` statement. Not very `logicless`.

@defunkt  @bobthecow

**Comment by locks** [comment]
An `if` by any other name would branch as conditionally.
Submit a PR with the suggested replacement implementation please, since I'm not familiar with the C# ecosystem.

**Comment by bobthecow** [comment]
Yeah, that's not Mustache at all. It's not even Handlebars, though it's closer to that… they use `{{#newline}}` as a (non-balanced) tag to indicate where to insert a newline in the template. It's rather … strange.

My vote is for removing it from the list entirely, even if a suitable replacement isn't found.

**Comment by ubershmekel** [comment]
I'll see if I can convert the JS version to C#.
