### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by Lukas238** [mustache/mustache.github.com#88]
I can't  find a way to use YAML with mustache.

I insalled this node version: https://www.npmjs.com/package/mustache

Works fine if I use a JSON.

This is the files I use:
**data.yml**
```
---
name: Hello
---
```

**template.html**
```
<html>
<body>
<h1>{{name}}</h1>
</body>
</html>
```

**Windows Command**
```$ mustache data.yml tempalte.html > template_compiled.html```

**Comment by iax7** [comment]
YAML support would be a killer feature!

**Comment by kag0** [comment]
@Lukas238 perhaps open an issue over in the repo that maintains that code https://github.com/janl/mustache.js
