### ISSUE TITLE
How to scape template variables?

### ISSUE THREAD

**Issue by posilva** [mustache/mustache.github.com#89]
Hi,

I have a template file, that i am using to generate some project files, and this template file has some  mustache variables that I do not want to expand/render at the generation phase,  because that should be done in a later stage when the project is already generated and we want to deploy it.

I would like to be able to escape some template variables to be able to use them only when application is deployed and not in the "generation" phase.   

Thank you 

Pedro

**Comment by jobol** [comment]
using "set delimiter" {{=<% %>=}}

**Comment by posilva** [comment]
Thank you, it's solved, what i do is before the escape variable i make the set delimiter to one different from the default and after the variable I will set again the default one.

**Comment by jgonggrijp** [comment]
Closing as answered.
