### ISSUE TITLE
Naming of # symbol

### ISSUE THREAD

**Issue by spapanik** [mustache/mustache.github.com#93]
In the documentation, the symbol # is called pound, which is really confusing in British English and in financial institutions, as it used for the GBP symbol (£).

**Comment by locks** [comment]
Hi! What do you suggest as a replacement?

**Comment by spapanik** [comment]
I think that number sign is probably the best, as it is the name used for it by unicode.org

**Comment by kellerdesign** [comment]
I say move to "octothorpe" instead.

**Comment by bobthecow** [comment]
“hashtag”

**Comment by jobol** [comment]
'sharp' sounds better

**Comment by jgonggrijp** [comment]
The source code of the manpages is in mustache/mustache so please take this discussion to https://github.com/mustache/mustache/issues/279.
